const fs = require("fs");
const path = require("path");
const pdfParse = require("pdf-parse");
const mongoose = require("mongoose");

const PDF = require("../models/PDF");
const Note = require("../models/Note");

const {
  generateNotes,
} = require("../services/noteService");

// Generate notes from selected PDF
exports.generateNotesFromPDF = async (
  req,
  res
) => {
  try {
    const { pdfId } = req.body;

    console.log(
      "========== NOTES DEBUG =========="
    );

    console.log("Received PDF ID:", pdfId);
    console.log(
      "Logged-in user:",
      req.user?.id
    );

    if (!pdfId) {
      return res.status(400).json({
        success: false,
        message: "PDF ID is required",
      });
    }

    if (
      !mongoose.Types.ObjectId.isValid(pdfId)
    ) {
      return res.status(400).json({
        success: false,
        message: "Invalid PDF ID",
      });
    }

    // Selected PDF logged-in user ki honi chahiye
    const pdf = await PDF.findOne({
      _id: pdfId,
      uploadedBy: req.user.id,
    });

    if (!pdf) {
      return res.status(404).json({
        success: false,
        message:
          "PDF not found or access denied",
      });
    }

    const pdfPath = path.join(
      __dirname,
      "..",
      pdf.filepath
    );

    console.log("Selected PDF:", pdf.title);
    console.log("PDF Path:", pdfPath);

    if (!fs.existsSync(pdfPath)) {
      return res.status(404).json({
        success: false,
        message: "PDF file not found",
      });
    }

    const buffer =
      fs.readFileSync(pdfPath);

    const pdfData =
      await pdfParse(buffer);

    if (!pdfData.text?.trim()) {
      return res.status(400).json({
        success: false,
        message:
          "No readable text found inside PDF",
      });
    }

    const generatedData =
      await generateNotes(pdfData.text);

    if (
      !generatedData ||
      !Array.isArray(
        generatedData.notes
      ) ||
      generatedData.notes.length === 0
    ) {
      return res.status(500).json({
        success: false,
        message:
          "Invalid notes generated by AI",
      });
    }

    // Har PDF ka apna separate note record
    const note =
      await Note.findOneAndUpdate(
        {
          pdfId: pdf._id,
        },
        {
          $set: {
            title:
              generatedData.title ||
              `Notes - ${pdf.title}`,
            notes: generatedData.notes,
          },
        },
        {
          new: true,
          upsert: true,
          runValidators: true,
          setDefaultsOnInsert: true,
        }
      );

    return res.status(200).json({
      success: true,
      message:
        "Notes Generated Successfully",
      note,
    });
  } catch (error) {
    console.error(
      "NOTES GENERATION ERROR:",
      error
    );

    return res.status(500).json({
      success: false,
      message: "Notes Generation Failed",
      error: error.message,
    });
  }
};

// Get notes using selected PDF ID
exports.getNotesByPDF = async (
  req,
  res
) => {
  try {
    const { pdfId } = req.params;

    console.log(
      "Fetching notes for PDF:",
      pdfId
    );

    if (!pdfId) {
      return res.status(400).json({
        success: false,
        message: "PDF ID is required",
      });
    }

    if (
      !mongoose.Types.ObjectId.isValid(pdfId)
    ) {
      return res.status(400).json({
        success: false,
        message: "Invalid PDF ID",
      });
    }

    // Verify PDF ownership
    const pdf = await PDF.findOne({
      _id: pdfId,
      uploadedBy: req.user.id,
    });

    if (!pdf) {
      return res.status(404).json({
        success: false,
        message:
          "PDF not found or access denied",
      });
    }

    // Sirf selected PDF ke notes fetch honge
    const note = await Note.findOne({
      pdfId: pdf._id,
    });

    if (!note) {
      return res.status(404).json({
        success: false,
        message:
          "No notes found for this PDF",
      });
    }

    return res.status(200).json({
      success: true,
      note,
    });
  } catch (error) {
    console.error(
      "NOTES FETCH ERROR:",
      error
    );

    return res.status(500).json({
      success: false,
      message: "Unable to fetch notes",
      error: error.message,
    });
  }
};